### ISSUE TITLE
Errors in console.

### ISSUE THREAD

**Issue by GDVE** [PFCraft/Mohist#102]
### **WorldEdit:**

[18:07:13] [Server thread/ERROR]: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.PlayerInputEvent@773de3d6 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[WorldEdit.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [WorldEdit.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [WorldEdit.jar:?]
	at com.sk89q.worldedit.WorldEdit.handleArmSwing(WorldEdit.java:665) [WorldEdit.jar:?]
	at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:146) [WorldEdit.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor15.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) [EventExecutor$2.class:1.2-cc99054]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:1.2-cc99054]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [SimplePluginManager.class:1.2-cc99054]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:261) [CraftEventFactory.class:1.2-cc99054]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [CraftEventFactory.class:1.2-cc99054]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:224) [CraftEventFactory.class:1.2-cc99054]
	at net.minecraft.network.NetHandlerPlayServer.func_175087_a(NetHandlerPlayServer.java:1605) [pa.class:?]
	at net.minecraft.network.play.client.CPacketAnimation.func_148833_a(SourceFile:32) [ly.class:?]
	at net.minecraft.network.play.client.CPacketAnimation.func_148833_a(SourceFile:9) [ly.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:453) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	... 23 more
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.WorldServer.getTileEntity(III)Lnet/minecraft/tileentity/TileEntity;
	at com.sk89q.worldedit.bukkit.adapter.impl.CraftBukkit_v1_6_R3.getBlock(CraftBukkit_v1_6_R3.java:229) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:405) ~[?:?]
	at com.sk89q.worldedit.internal.LocalWorldAdapter.getBlock(LocalWorldAdapter.java:235) ~[?:?]
	at com.sk89q.worldedit.util.TargetBlock.getSolidTargetBlock(TargetBlock.java:151) ~[?:?]
	at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.getSolidBlockTrace(AbstractPlayerActor.java:342) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:406) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	... 23 more

### **And this error with EventHelper by gamerForEA:**
[18:04:59] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$LeftClickBlock@2b2a6f05:
java.lang.NoSuchMethodError: com.gamerforea.eventhelper.util.EventUtils.cantPlace(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;)Z
	at team.chisel.common.item.ChiselController.setVariation(ChiselController.java:120) ~[ChiselController.class:?]
	at team.chisel.common.item.ChiselController.setAll(ChiselController.java:104) ~[ChiselController.class:?]
	at team.chisel.common.item.ChiselController.onPlayerInteract(ChiselController.java:79) ~[ChiselController.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_ChiselController_onPlayerInteract_LeftClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:1.2-cc99054]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) [EventBus.class:1.2-cc99054]
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1008) [ForgeHooks.class:1.2-cc99054]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:157) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1042) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:453) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[18:04:59] [Server thread/ERROR]: Index: 1 Listeners:
[18:04:59] [Server thread/ERROR]: 0: NORMAL
[18:04:59] [Server thread/ERROR]: 1: ASM: class team.chisel.common.item.ChiselController onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[18:04:59] [Server thread/ERROR]: 2: ASM: mod.chiselsandbits.events.EventPlayerInteract@66e69839 interaction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[18:04:59] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.gamerforea.eventhelper.util.EventUtils.cantPlace(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;)Z
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:453) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: com.gamerforea.eventhelper.util.EventUtils.cantPlace(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;)Z
	at team.chisel.common.item.ChiselController.setVariation(ChiselController.java:120) ~[ChiselController.class:?]
	at team.chisel.common.item.ChiselController.setAll(ChiselController.java:104) ~[ChiselController.class:?]
	at team.chisel.common.item.ChiselController.onPlayerInteract(ChiselController.java:79) ~[ChiselController.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_ChiselController_onPlayerInteract_LeftClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:1.2-cc99054]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) ~[EventBus.class:1.2-cc99054]
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1008) ~[ForgeHooks.class:1.2-cc99054]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:157) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1042) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[18:04:59] [Server thread/INFO]: MuTik issued server command: /fly
[18:04:59] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$LeftClickBlock@18586367:
java.lang.NoSuchMethodError: com.gamerforea.eventhelper.util.EventUtils.cantPlace(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;)Z
	at team.chisel.common.item.ChiselController.setVariation(ChiselController.java:120) ~[ChiselController.class:?]
	at team.chisel.common.item.ChiselController.setAll(ChiselController.java:104) ~[ChiselController.class:?]
	at team.chisel.common.item.ChiselController.onPlayerInteract(ChiselController.java:79) ~[ChiselController.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_ChiselController_onPlayerInteract_LeftClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:1.2-cc99054]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) [EventBus.class:1.2-cc99054]
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1008) [ForgeHooks.class:1.2-cc99054]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:157) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1042) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:453) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[18:04:59] [Server thread/ERROR]: Index: 1 Listeners:
[18:04:59] [Server thread/ERROR]: 0: NORMAL
[18:04:59] [Server thread/ERROR]: 1: ASM: class team.chisel.common.item.ChiselController onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[18:04:59] [Server thread/ERROR]: 2: ASM: mod.chiselsandbits.events.EventPlayerInteract@66e69839 interaction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[18:04:59] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.gamerforea.eventhelper.util.EventUtils.cantPlace(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;)Z
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:453) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: com.gamerforea.eventhelper.util.EventUtils.cantPlace(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;)Z
	at team.chisel.common.item.ChiselController.setVariation(ChiselController.java:120) ~[ChiselController.class:?]
	at team.chisel.common.item.ChiselController.setAll(ChiselController.java:104) ~[ChiselController.class:?]
	at team.chisel.common.item.ChiselController.onPlayerInteract(ChiselController.java:79) ~[ChiselController.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_ChiselController_onPlayerInteract_LeftClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:1.2-cc99054]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) ~[EventBus.class:1.2-cc99054]
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1008) ~[ForgeHooks.class:1.2-cc99054]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:157) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1042) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[18:05:00] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$LeftClickBlock@13b01086:
java.lang.NoSuchMethodError: com.gamerforea.eventhelper.util.EventUtils.cantPlace(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;)Z
	at team.chisel.common.item.ChiselController.setVariation(ChiselController.java:120) ~[ChiselController.class:?]
	at team.chisel.common.item.ChiselController.setAll(ChiselController.java:104) ~[ChiselController.class:?]
	at team.chisel.common.item.ChiselController.onPlayerInteract(ChiselController.java:79) ~[ChiselController.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_ChiselController_onPlayerInteract_LeftClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:1.2-cc99054]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) [EventBus.class:1.2-cc99054]
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1008) [ForgeHooks.class:1.2-cc99054]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:157) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1042) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:453) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[18:05:00] [Server thread/ERROR]: Index: 1 Listeners:
[18:05:00] [Server thread/ERROR]: 0: NORMAL
[18:05:00] [Server thread/ERROR]: 1: ASM: class team.chisel.common.item.ChiselController onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[18:05:00] [Server thread/ERROR]: 2: ASM: mod.chiselsandbits.events.EventPlayerInteract@66e69839 interaction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[18:05:00] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.gamerforea.eventhelper.util.EventUtils.cantPlace(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;)Z
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:453) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: com.gamerforea.eventhelper.util.EventUtils.cantPlace(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;)Z
	at team.chisel.common.item.ChiselController.setVariation(ChiselController.java:120) ~[ChiselController.class:?]
	at team.chisel.common.item.ChiselController.setAll(ChiselController.java:104) ~[ChiselController.class:?]
	at team.chisel.common.item.ChiselController.onPlayerInteract(ChiselController.java:79) ~[ChiselController.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_ChiselController_onPlayerInteract_LeftClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:1.2-cc99054]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) ~[EventBus.class:1.2-cc99054]
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1008) ~[ForgeHooks.class:1.2-cc99054]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:157) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1042) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by GDVE** [comment]
**### The compass does not work (teleport through WorldEdit blocks)**

[18:38:44 ERROR]: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.PlayerInputEvent@2d1c6483 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [WorldEdit.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [WorldEdit.jar:?]
        at com.sk89q.worldedit.WorldEdit.handleRightClick(WorldEdit.java:677) [WorldEdit.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:164) [WorldEdit.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor15.execute(Unknown Source) [?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) [EventExecutor$2.class:1.2-cc99054]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:1.2-cc99054]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [SimplePluginManager.class:1.2-cc99054]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:261) [CraftEventFactory.class:1.2-cc99054]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [CraftEventFactory.class:1.2-cc99054]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:224) [CraftEventFactory.class:1.2-cc99054]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:1153) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) [mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) [mb.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:453) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 23 more
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.WorldServer.getTileEntity(III)Lnet/minecraft/tileentity/TileEntity;
        at com.sk89q.worldedit.bukkit.adapter.impl.CraftBukkit_v1_6_R3.getBlock(CraftBukkit_v1_6_R3.java:229) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:405) ~[?:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.passThroughForwardWall(AbstractPlayerActor.java:393) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:441) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 23 more

**Comment by Mgazul** [comment]
This should be fixed by EventHandler
