### ISSUE TITLE
Server crashed in starting

### ISSUE THREAD

**Issue by GDVE** [PFCraft/Mohist#11]
[19:15:34 ERROR] [Mohist]: Encountered an unexpected exception
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=woodtype, clazz=class jds.bibliocraft.blocks.BiblioWoodBlock$EnumWoodType, values=[oak, spruce, birch, jungle, acacia, darkoak, framed]} as it does not exist in ExtendedBlockState{block=bibliocraft:bookcase, properties=[woodtype]}
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201) ~[awu$a.class:?]
        at jds.bibliocraft.blocks.BiblioWoodBlock.func_176201_c(BiblioWoodBlock.java:104) ~[BiblioWoodBlock.class:?]
        at net.minecraftforge.registries.GameData$BlockCallbacks.onAdd(GameData.java:337) ~[GameData$BlockCallbacks.class:14.23.5.2824-0.0.5a]
        at net.minecraftforge.registries.GameData$BlockCallbacks.onAdd(GameData.java:305) ~[GameData$BlockCallbacks.class:14.23.5.2824-0.0.5a]
        at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:350) ~[ForgeRegistry.class:14.23.5.2824-0.0.5a]
        at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281) ~[ForgeRegistry.class:14.23.5.2824-0.0.5a]
        at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:515) ~[ForgeRegistry.class:14.23.5.2824-0.0.5a]
        at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:561) ~[GameData.class:14.23.5.2824-0.0.5a]
        at net.minecraftforge.registries.GameData.freezeData(GameData.java:237) ~[GameData.class:14.23.5.2824-0.0.5a]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753) ~[Loader.class:14.23.5.2824-0.0.5a]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) ~[FMLServerHandler.class:14.23.5.2824-0.0.5a]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) ~[FMLCommonHandler.class:14.23.5.2824-0.0.5a]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:230) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[19:15:34 ERROR] [Mohist]: This crash report has been saved to: /root/servers/mohist/./crash-reports/crash-2019-04-02_19.15.34-server.txt
[19:15:34 INFO] [Mohist]: Stopping server
[19:15:34 INFO] [Mohist]: Saving players
[19:15:34 INFO] [Mohist]: Saving worlds

**Comment by Mgazul** [comment]
bibliocraft Temporarily unavailable, please wait for repair

**Comment by Mgazul** [comment]
already fixed
