### ISSUE TITLE
Backpacks reset when server restarts.

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#117]
When the server restarts all items in the backpacks gets deleted on the BackPacks mod.

This mod is on the Tekxit 3 modpack on Technic.
Using latest version of Mohist.

**Comment by Zilacon** [comment]
Not sure if related but i found this on console:
```
[01:13:22] [File IO Thread/WARN]: java.io.IOException: No such file or directory
[01:13:22] [File IO Thread/WARN]: 	at java.io.File.createNewFile(File.java:1012)
[01:13:22] [File IO Thread/WARN]: 	at net.minecraft.world.storage.MapStorage.lambda$saveData$0(MapStorage.java:117)
[01:13:22] [File IO Thread/WARN]: 	at net.minecraft.world.storage.MapStorage$$Lambda$2831.000000004E336800.func_75814_c(Unknown Source)
[01:13:22] [File IO Thread/WARN]: 	at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(ThreadedFileIOBase.java:42)
[01:13:22] [File IO Thread/WARN]: 	at net.minecraft.world.storage.ThreadedFileIOBase.run(ThreadedFileIOBase.java:31)
[01:13:22] [File IO Thread/WARN]: 	at java.lang.Thread.run(Thread.java:813)
```
