### ISSUE TITLE
MCMMO Plugin does not start.

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#118]
```
[01:31:36] [Server thread/INFO]: Enabling mcMMO v1.5.10
[01:31:37] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[01:31:37] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
[01:31:37] [Server thread/WARN]: 	at net.minecraft.item.crafting.ShapelessRecipes.toBukkitRecipe(ShapelessRecipes.java:153)
[01:31:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.inventory.RecipeIterator.next(RecipeIterator.java:33)
[01:31:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.inventory.RecipeIterator.next(RecipeIterator.java:11)
[01:31:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getRecipesFor(CraftServer.java:986)
[01:31:37] [Server thread/WARN]: 	at com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:283)
[01:31:37] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfig.loadKeys(RepairConfig.java:139)
[01:31:37] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfig.<init>(RepairConfig.java:24)
[01:31:37] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfigManager.<init>(RepairConfigManager.java:34)
[01:31:37] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:411)
[01:31:37] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:145)
[01:31:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:172)
[01:31:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:322)
[01:31:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:397)
[01:31:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:394)
[01:31:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335)
[01:31:37] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:436)
[01:31:37] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:120)
[01:31:37] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:140)
[01:31:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:308)
[01:31:37] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:311)
[01:31:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:599)
[01:31:37] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:813)
[01:31:37] [Server thread/INFO]: Disabling mcMMO v1.5.10
[01:31:37] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.10 (Is it up to date?)
java.lang.NullPointerException: null
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:245) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:174) ~[JavaPlugin.class:1.2-bed4649]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:355) [JavaPluginLoader.class:1.2-bed4649]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [SimplePluginManager.class:1.2-bed4649]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:420) [SimplePluginManager.class:1.2-bed4649]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:199) [mcMMO-Classic-122.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:172) [JavaPlugin.class:1.2-bed4649]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:322) [JavaPluginLoader.class:1.2-bed4649]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:397) [SimplePluginManager.class:1.2-bed4649]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:394) [CraftServer.class:1.2-bed4649]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [CraftServer.class:1.2-bed4649]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:436) [bfb.class:?]
	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:120) [bfc.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:140) [bfb.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:308) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:311) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:599) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```

**Comment by Mgazul** [comment]
McMMO v1.5.10 is too old, please use the latest version to test, or give me the download link for 1.5.10

**Comment by Zilacon** [comment]
1.5.10 is the latest version for 1.12.2 according to their spigot plugin page.
https://www.spigotmc.org/resources/official-mcmmo-classic.2445/
The 1.5.08 download link downloads 1.5.10.

The most recent version of MCMMO is MCMMO-Overhauled which their devs have confirmed to me does not support 1.12.2 yet.
