### ISSUE TITLE
HolographicDisplays is erroring again...

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#119]
```
[01:32:11] [Server thread/WARN]: [HolographicDisplays] Unable to get a stack trace element, please inform the developer. You will only see this error once and a fallback method will be used.
java.lang.NoSuchMethodException: java.lang.Throwable.getStackTraceDepth()
	at java.lang.Class.newNoSuchMethodException(Class.java:562) ~[?:1.8.0_212]
	at java.lang.Class.throwExceptionOrReturnNull(Class.java:1195) ~[?:1.8.0_212]
	at java.lang.Class.getMethodHelper(Class.java:1259) ~[?:1.8.0_212]
	at java.lang.Class.getDeclaredMethod(Class.java:931) ~[?:1.8.0_212]
	at red.mohist.common.asm.remap.proxy.ProxyClass.getDeclaredMethod(ProxyClass.java:31) ~[ProxyClass.class:1.2-bed4649]
	at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.init(ReflectMethod.java:36) ~[HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.invoke(ReflectMethod.java:42) ~[HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectionUtils.getStackTraceElement(ReflectionUtils.java:58) [HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.EntityNMSArmorStand.func_145782_y(EntityNMSArmorStand.java:155) [HolographicDisplays.jar:?]
	at net.minecraft.network.play.server.SPacketEntityTeleport.<init>(SourceFile:22) [kt.class:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.EntityNMSArmorStand.setLocationNMS(EntityNMSArmorStand.java:220) [HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:100) [HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:104) [HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:314) [HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:261) [HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.task.StartupLoadHologramsTask.run(StartupLoadHologramsTask.java:38) [HolographicDisplays.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:73) [CraftTask.class:1.2-bed4649]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:426) [CraftScheduler.class:1.2-bed4649]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:453) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```

**Comment by Mgazul** [comment]
Under what circumstances will warnings appear

**Comment by Zilacon** [comment]
This appears on every server start up.

**Comment by Mgazul** [comment]
Error cannot be reproduced, make sure you are using the latest build

**Comment by Zilacon** [comment]
I am using the latest build. Do you have holograms setup somewhere in the world?

**Comment by Mgazul** [comment]
Yes, I've created about 10 new ones, just text

**Comment by Mgazul** [comment]
It needs to be tested again, maybe fixed

**Comment by s091424** [comment]
I got the same issue, 
using PaperSpigot-1.12.2-b1380 and plugin version 2.3.2
`[12:17:37 WARN]: [HolographicDisplays] Unable to get a stack trace element, please inform the developer. You will only see this error once and a fallback method will be used.
java.lang.NoSuchMethodException: java.lang.Throwable.getStackTraceDepth()
        at java.lang.Class.newNoSuchMethodException(Class.java:561) ~[?:1.8.0_202]
        at java.lang.Class.throwExceptionOrReturnNull(Class.java:1194) ~[?:1.8.0_202]
        at java.lang.Class.getMethodHelper(Class.java:1258) ~[?:1.8.0_202]
        at java.lang.Class.getDeclaredMethod(Class.java:930) ~[?:1.8.0_202]
        at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.init(ReflectMethod.java:36) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.invoke(ReflectMethod.java:42) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectionUtils.getStackTraceElement(ReflectionUtils.java:58) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.EntityNMSArmorStand.getId(EntityNMSArmorStand.java:155) ~[?:?]
        at net.minecraft.server.v1_12_R1.PacketPlayOutEntityTeleport.<init>(SourceFile:22) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.EntityNMSArmorStand.setLocationNMS(EntityNMSArmorStand.java:220) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:100) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:104) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshSingleLines(CraftHologram.java:284) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.appendTextLine(CraftHologram.java:134) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.appendTextLine(CraftHologram.java:40) ~[?:?]
        at me.clayclaw.resmanagement.bukkit.block.ResBlockCache.load(ResBlockCache.java:81) ~[?:?]
        at me.clayclaw.resmanagement.bukkit.listener.block.BlockListener.lambda$onChunkLoad$2(BlockListener.java:166) ~[?:?]
        at me.clayclaw.resmanagement.bukkit.listener.block.BlockListener$$Lambda$264.0000000012D68BA0.accept(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_202]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_202]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_202]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_202]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:496) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:486) ~[?:1.8.0_202]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_202]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:241) ~[?:1.8.0_202]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_202]
        at me.clayclaw.resmanagement.bukkit.listener.block.BlockListener.onChunkLoad(BlockListener.java:164) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor189.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:995) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:54) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.lambda$syncChunkLoad$0(ChunkIOExecutor.java:18) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor$$Lambda$197.0000000012CC9FD0.get(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:69) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:181) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:625) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.Location.getChunk(Location.java:82) ~[PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at me.clayclaw.resmanagement.bukkit.block.ResBlockService.register(ResBlockService.java:22) ~[?:?]
        at me.clayclaw.resmanagement.storage.sql.SQLStorageService.loadResPOJO(SQLStorageService.java:129) ~[?:?]
        at me.clayclaw.resmanagement.storage.sql.SQLStorageService.lambda$new$0(SQLStorageService.java:73) ~[?:?]
        at me.clayclaw.resmanagement.storage.sql.SQLStorageService$$Lambda$224.00000000108B34C0.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) [PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-1.12.2-b1380.jar:git-Paper-1380]
        at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]`
it occurs when hologram.appendTextLine() is called
