### ISSUE TITLE
Compatibility issues with Phosphor and TickDynamic.

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#120]
Phosphor:
```
[06:42:19] [PaperSpigot - Lighting Thread/WARN]: Something (likely another mod) has attempted to modify the world's state from the wrong thread!
This is *bad practice* and can cause severe issues in your game. Phosphor has done as best as it can to mitigate this violation, but it may negatively impact performance or introduce stalls.
In a future release, this violation may result in a hard crash instead of the current soft warning. You should report this issue to our issue tracker with the following stacktrace information.
(If you are aware you have misbehaving mods and cannot resolve this issue, you can safely disable this warning by setting `enable_illegal_thread_access_warnings` to `false` in Phosphor's configuration file for the time being.)
java.lang.IllegalAccessException: World is owned by 'Server thread' (ID: 333), but was accessed from thread 'PaperSpigot - Lighting Thread' (ID: 465)
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.acquireLock(LightingEngine.java:204) [LightingEngine.class:?]
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.scheduleLightUpdate(LightingEngine.java:131) [LightingEngine.class:?]
	at net.minecraft.world.World.handler$checkLightFor$zzf000(World.java:4519) [amu.class:?]
	at net.minecraft.world.World.func_180500_c(World.java) [amu.class:?]
	at net.minecraft.world.chunk.Chunk.updateSkylightNeighborHeight(Chunk.java:2079) [axw.class:?]
	at net.minecraft.world.chunk.Chunk.checkSkylightNeighborHeight(Chunk.java:2066) [axw.class:?]
	at net.minecraft.world.chunk.Chunk.recheckGapsSkylightNeighborHeight(Chunk.java:2052) [axw.class:?]
	at net.minecraft.world.chunk.Chunk.recheckGapsForColumn(Chunk.java:2030) [axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_150803_c(Chunk.java:2001) [axw.class:?]
	at net.minecraft.world.chunk.Chunk.access$000(Chunk.java:50) [axw.class:?]
	at net.minecraft.world.chunk.Chunk$1.run(Chunk.java:322) [axw$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```

Tick Dynamic:
```
[06:42:18] [Server thread/WARN]: java.lang.Throwable
[06:42:18] [Server thread/WARN]: 	at java.lang.Thread.dumpStack(Thread.java:490)
[06:42:18] [Server thread/WARN]: 	at com.wildex999.tickdynamic.listinject.ListManager.remove(ListManager.java:374)
[06:42:18] [Server thread/WARN]: 	at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:57)
[06:42:18] [Server thread/WARN]: 	at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:9)
[06:42:18] [Server thread/WARN]: 	at net.minecraft.world.World.func_72939_s(World.java:2096)
[06:42:18] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:839)
[06:42:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:908)
[06:42:18] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:453)
[06:42:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801)
[06:42:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648)
[06:42:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:813)
```
```
[06:40:48] [Server thread/WARN]: java.lang.Throwable
[06:40:48] [Server thread/WARN]: 	at java.lang.Thread.dumpStack(Thread.java:490)
[06:40:48] [Server thread/WARN]: 	at com.wildex999.tickdynamic.listinject.ListManager.remove(ListManager.java:374)
[06:40:48] [Server thread/WARN]: 	at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:57)
[06:40:48] [Server thread/WARN]: 	at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:9)
[06:40:48] [Server thread/WARN]: 	at net.minecraft.world.World.func_72973_f(World.java:1562)
[06:40:48] [Server thread/WARN]: 	at net.minecraft.server.management.PlayerList.moveToWorld(PlayerList.java:728)
[06:40:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:700)
[06:40:48] [Server thread/WARN]: 	at com.earth2me.essentials.paperlib.features.asyncteleport.AsyncTeleportSync.teleportAsync(AsyncTeleportSync.java:13)
[06:40:48] [Server thread/WARN]: 	at com.earth2me.essentials.paperlib.environments.Environment.teleport(Environment.java:79)
[06:40:48] [Server thread/WARN]: 	at com.earth2me.essentials.paperlib.PaperLib.teleportAsync(PaperLib.java:86)
[06:40:48] [Server thread/WARN]: 	at com.earth2me.essentials.Teleport.now(Teleport.java:143)
[06:40:48] [Server thread/WARN]: 	at com.earth2me.essentials.Teleport.teleport(Teleport.java:202)
[06:40:48] [Server thread/WARN]: 	at com.earth2me.essentials.Teleport.teleport(Teleport.java:158)
[06:40:48] [Server thread/WARN]: 	at com.earth2me.essentials.commands.Commandhome.goHome(Commandhome.java:97)
[06:40:48] [Server thread/WARN]: 	at com.earth2me.essentials.commands.Commandhome.run(Commandhome.java:60)
[06:40:48] [Server thread/WARN]: 	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:161)
[06:40:48] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:545)
[06:40:48] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:458)
[06:40:48] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[06:40:48] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:133)
[06:40:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:668)
[06:40:48] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1570)
[06:40:48] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1417)
[06:40:48] [Server thread/WARN]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:51)
[06:40:48] [Server thread/WARN]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:12)
[06:40:48] [Server thread/WARN]: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[06:40:48] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[06:40:48] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[06:40:48] [Server thread/WARN]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[06:40:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858)
[06:40:48] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:453)
[06:40:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801)
[06:40:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648)
[06:40:48] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:813)
```
```
[06:38:49] [Server thread/WARN]: Failed to remove: net.minecraft.tileentity.TileEntitySign@8e766a70 as it does not exist in the list.
[06:38:49] [Server thread/WARN]: Failed to remove: net.minecraft.tileentity.TileEntitySign@c865fe33 as it does not exist in the list.
[06:38:49] [Server thread/WARN]: Failed to remove: net.minecraft.tileentity.TileEntitySign@5db0ffac as it does not exist in the list.
[06:38:49] [Server thread/WARN]: Failed to remove: net.minecraft.tileentity.TileEntitySign@91ac689e as it does not exist in the list.
[06:38:49] [Server thread/WARN]: Failed to remove: net.minecraft.tileentity.TileEntitySign@c9b8ef19 as it does not exist in the list.
[06:38:49] [Server thread/WARN]: Failed to remove: net.minecraft.tileentity.TileEntitySign@ec6cf26 as it does not exist in the list.
[06:38:49] [Server thread/WARN]: Failed to remove: net.minecraft.tileentity.TileEntitySign@643a827e as it does not exist in the list.
[06:38:49] [Server thread/WARN]: Failed to remove: net.minecraft.tileentity.TileEntitySign@d3455a17 as it does not exist in the list.
[06:38:49] [Server thread/WARN]: Failed to remove: net.minecraft.tileentity.TileEntitySign@c61ef9fb as it does not exist in the list.
```

**Comment by Mgazul** [comment]
Jellysquid clashes with a patch of paper, and you can turn off the warning

**Comment by Zilacon** [comment]
What is jellysquid and how do i turn off the warning?

**Comment by Mgazul** [comment]
tickdynamic Can't be fixed
phosphor already fixed
