### ISSUE TITLE
Essentials & other teleport plugins not working [High Priority]

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#125]
So after i updated to the recent versions the commands from random teleport plugins, and plugins like essentials for warps/homes/teleporting does not work. This error comes up when using essentials.

Going from latest to build 390 fixed this problem.

```
[21:36:39] [Server thread/INFO]: Zilacon issued server command: /home home
[21:36:39] [Server thread/ERROR]: Command home failed:
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org.bukkit.World$ChunkLoadCallback
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:881) ~[?:1.8.0_212]
	at com.earth2me.essentials.paperlib.features.asyncchunks.AsyncChunksPaper_9_12.getChunkAtAsync(AsyncChunksPaper_9_12.java:19) ~[EssentialsX-2.17.0.3.jar:?]
	at com.earth2me.essentials.paperlib.environments.Environment.getChunkAtAsync(Environment.java:75) ~[EssentialsX-2.17.0.3.jar:?]
	at com.earth2me.essentials.paperlib.PaperLib.getChunkAtAsync(PaperLib.java:132) ~[EssentialsX-2.17.0.3.jar:?]
	at com.earth2me.essentials.paperlib.features.asyncteleport.AsyncTeleportPaper.teleportAsync(AsyncTeleportPaper.java:16) ~[EssentialsX-2.17.0.3.jar:?]
	at com.earth2me.essentials.paperlib.environments.Environment.teleport(Environment.java:79) ~[EssentialsX-2.17.0.3.jar:?]
	at com.earth2me.essentials.paperlib.PaperLib.teleportAsync(PaperLib.java:86) ~[EssentialsX-2.17.0.3.jar:?]
	at com.earth2me.essentials.Teleport.now(Teleport.java:143) ~[EssentialsX-2.17.0.3.jar:?]
	at com.earth2me.essentials.Teleport.teleport(Teleport.java:202) ~[EssentialsX-2.17.0.3.jar:?]
	at com.earth2me.essentials.Teleport.teleport(Teleport.java:158) ~[EssentialsX-2.17.0.3.jar:?]
	at com.earth2me.essentials.commands.Commandhome.goHome(Commandhome.java:97) ~[EssentialsX-2.17.0.3.jar:?]
	at com.earth2me.essentials.commands.Commandhome.run(Commandhome.java:51) ~[EssentialsX-2.17.0.3.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:161) ~[EssentialsX-2.17.0.3.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:545) [EssentialsX-2.17.0.3.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:458) [EssentialsX-2.17.0.3.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.2-2ab1ec7]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:133) [SimpleCommandMap.class:1.2-2ab1ec7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:688) [CraftServer.class:1.2-2ab1ec7]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1570) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1417) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:51) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:12) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:458) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
Caused by: java.lang.NoClassDefFoundError: org.bukkit.World$ChunkLoadCallback
	at java.lang.invoke.MethodType.throwNoClassDefFoundError(MethodType.java:380) ~[?:1.8.0_212]
	at java.lang.invoke.MethodType.vmResolveFromMethodDescriptorString(MethodType.java:362) ~[?:1.8.0_212]
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:752) ~[?:1.8.0_212]
	... 30 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.World$ChunkLoadCallback
	at java.lang.Class.forNameImpl(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:416) ~[?:1.8.0_212]
	at java.lang.invoke.MethodType.nonPrimitiveClassFromString(MethodType.java:399) ~[?:1.8.0_212]
	at java.lang.invoke.MethodType.parseIntoClass(MethodType.java:430) ~[?:1.8.0_212]
	at java.lang.invoke.MethodType.parseIntoClasses(MethodType.java:489) ~[?:1.8.0_212]
	at java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:309) ~[?:1.8.0_212]
	at java.lang.invoke.MethodType.vmResolveFromMethodDescriptorString(MethodType.java:358) ~[?:1.8.0_212]
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:752) ~[?:1.8.0_212]
	... 30 more
```
@Mgazul @azbh111

**Comment by Flashback083** [comment]
I use Mohist-1.2-2ab1ec7 and homes works well

**Comment by Zilacon** [comment]
I was using that version and it did not work due to the above error. What plugin are you using for teleportation?

**Comment by Flashback083** [comment]
For homes i use Essentials

**Comment by Zilacon** [comment]
EssentialsX?

**Comment by Zilacon** [comment]
Flashback is on essentials version 2.15.55
I am on essentials version 2.17.0.3

So the newer versions have an issue with the latest version but the older versions do not (have not tested older version myself)

**Comment by Mgazul** [comment]
This is because ess defines mohist as paper, which makes it impossible to read something (because mohist does not exist).
