### ISSUE TITLE
Citizens

### ISSUE THREAD

**Issue by Kerlann** [PFCraft/Mohist#129]
Mohist-1.2-56f1df2-universal.jar

[06:34:45 WARN]: [Citizens] Task #961 for Citizens v2.0.25-SNAPSHOT (build 1708) generated an exception
java.lang.AbstractMethodError: Method net/citizensnpcs/nms/v1_12_R1/entity/EntityHumanNPC.getProfile()Lcom/mojang/authlib/GameProfile; is abstract
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.getProfile(EntityHumanNPC.java) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin.setNPCTexture(Skin.java:383) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin.apply(Skin.java:90) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.HumanController.createEntity(HumanController.java:57) ~[?:?]
        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:232) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:150) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
        at net.citizensnpcs.Citizens$3.run(Citizens.java:331) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:73) ~[CraftTask.class:1.2-56f1df2]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:426) [CraftScheduler.class:1.2-56f1df2]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:458) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by Mgazul** [comment]
Fixed
