### ISSUE TITLE
Issue with NMS

### ISSUE THREAD

**Issue by GDVE** [PFCraft/Mohist#13]
[19:22:16 INFO] [Mohist]: Enabling HolographicDisplays v2.3.2
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/World
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at java.lang.Class.forName0(Native Method)
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at java.lang.Class.forName(Class.java:264)
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at com.gmail.filoghost.holographicdisplays.HolographicDisplays.onEnable(HolographicDisplays.java:115)
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:248)
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:313)
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:394)
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:407)
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:315)
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:464)
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:419)
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:359)
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:281)
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635)
[19:22:16] [Server thread/INFO] [STDERR]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:onEnable:117]: 	at java.lang.Thread.run(Thread.java:748)
[19:22:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.World
[19:22:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108)
[19:22:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:103)
[19:22:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:22:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:22:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 14 more
[19:22:16] [Server thread/INFO] [STDOUT]: [com.gmail.filoghost.holographicdisplays.HolographicDisplays:printWarnAndDisable:215]: 
 
******************************************************
     HolographicDisplays was unable to instantiate
     the NMS manager. The plugin will be disabled.
******************************************************

**Comment by GDVE** [comment]
Big thanks for your work!

**Comment by Mgazul** [comment]
Temporarily does not support nms, you can refactor the plugin to use mcp instead of nms

**Comment by GDVE** [comment]
When is nms support planned?
