### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by CKATEPTb** [PFCraft/Mohist#131]
[21:40:41 WARN]: [Essentials] Task #55 for Essentials v2.17.0.3 generated an exception
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/bukkit/World$ChunkLoadCallback
        at com.earth2me.essentials.paperlib.features.asyncchunks.AsyncChunksPaper_9_12.getChunkAtAsync(AsyncChunksPaper_9_12.java:19) ~[?:?]
        at com.earth2me.essentials.paperlib.environments.Environment.getChunkAtAsync(Environment.java:75) ~[?:?]
        at com.earth2me.essentials.paperlib.PaperLib.getChunkAtAsync(PaperLib.java:132) ~[?:?]
        at com.earth2me.essentials.paperlib.features.asyncteleport.AsyncTeleportPaper.teleportAsync(AsyncTeleportPaper.java:16) ~[?:?]
        at com.earth2me.essentials.paperlib.environments.Environment.teleport(Environment.java:79) ~[?:?]
        at com.earth2me.essentials.paperlib.PaperLib.teleportAsync(PaperLib.java:86) ~[?:?]
        at com.earth2me.essentials.Teleport.now(Teleport.java:131) ~[?:?]
        at com.earth2me.essentials.Teleport.now(Teleport.java:108) ~[?:?]
        at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$NewPlayerTeleport.run(EssentialsSpawnPlayerListener.java:141) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:73) ~[CraftTask.class:1.2-d85f790]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:426) [CraftScheduler.class:1.2-d85f790]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:458) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/World$ChunkLoadCallback
        ... 16 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.World$ChunkLoadCallback
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PluginClassLoader.class:1.2-d85f790]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[PluginClassLoader.class:1.2-d85f790]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
        ... 16 more

**Comment by CKATEPTb** [comment]
https://github.com/PaperMC/PaperLib/blob/1ac7769a0d5f9f6076e74f05d880eb577448eb77/src/main/java/io/papermc/lib/PaperLib.java#L35 use reflection remap to fix it

**Comment by CKATEPTb** [comment]
https://github.com/PFCraft/Mohist/blob/2dfcc8252de036a302762a9ad9683dd5dcaef87c/src/main/java/org/bukkit/plugin/java/PluginClassLoader.java#L90 override forName

**Comment by Mgazul** [comment]
This is because ess defines mohist as paper, which makes it impossible to read something (because mohist does not exist).
Please use the essentials - 2.15

**Comment by CKATEPTb** [comment]
> This is because ess defines mohist as paper, which makes it impossible to read something (because mohist does not exist).
> Please use the essentials - 2.15

i know, BUT need to fix it.
if Class.forName(paperconfig)
throw new classnotfound
OR FIX ESSENTIALS PaperLib
![image](https://user-images.githubusercontent.com/33106029/61435744-e87d3980-a941-11e9-9289-35c835665955.png)
