### ISSUE TITLE
The client has sent too many requests within a certain amount of time

### ISSUE THREAD

**Issue by CKATEPTb** [PFCraft/Mohist#136]
```
[15:51:29 WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@6a4c9851[id=49a4dad2-7cad-4614-b43c-cd59099bcd20,name=CKATEPTb,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[YggdrasilAuthenticationService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [YggdrasilMinecraftSessionService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [YggdrasilMinecraftSessionService.class:?]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:216) [CraftPlayerProfile.class:1.2-db75aa6]
        at com.destroystokyo.paper.profile.PlayerProfile.complete(PlayerProfile.java:127) [PlayerProfile.class:1.2-db75aa6]
        at net.minecraft.server.network.NetHandlerLoginServer$LoginHandler.fireEvents(NetHandlerLoginServer.java:329) [pc$LoginHandler.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer$3.run(NetHandlerLoginServer.java:271) [pc$3.class:?]
```

**Comment by Zilacon** [comment]
I also have this issue.

**Comment by Protoxy22** [comment]
Same issue !
