### ISSUE TITLE
ConcurrentModificationException with LagAssist plugin.

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#138]
```
[22:10:55] [Craft Scheduler Thread - 190/WARN]: [LagAssist] Plugin LagAssist v2.18.1 generated an exception while executing task 14
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_212]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_212]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getEntities(CraftWorld.java:723) ~[CraftWorld.class:1.2-bbe9138]
	at cx.sfy.LagAssist.stacker.StackMonitor.lambda$1(StackMonitor.java:45) ~[?:?]
	at cx.sfy.LagAssist.stacker.StackMonitor$$Lambda$2573.0000000034923210.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:73) ~[CraftTask.class:1.2-bbe9138]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:1.2-bbe9138]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [ServerSchedulerReportingWrapper.class:1.2-bbe9138]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```

**Comment by Zilacon** [comment]
The plugins chunk limiter and dynamic range and possible others are not working correctly due to the plugin not identifying mohist as paperspigot.
