### ISSUE TITLE
Error and warn plugins

### ISSUE THREAD

**Issue by ErriourRU** [PFCraft/Mohist#144]
Hi. I have warn from WorldEdit (or FAWE?)
`[01:11:47 INFO]: Enabling WorldEdit v6.1.7;dd00bb1
[01:11:47 WARN]: Error in factory method for GroupManagerResolver
java.lang.NoClassDefFoundError: org/anjocaido/groupmanager/permissions/AnjoPermissionsHandler
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_212]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_212]
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048) ~[?:1.8.0_212]
        at java.lang.Class.getMethod0(Class.java:3018) ~[?:1.8.0_212]
        at java.lang.Class.getMethod(Class.java:1784) ~[?:1.8.0_212]
        at red.mohist.common.asm.remap.proxy.ProxyClass.getMethod(ProxyClass.java:38) ~[ProxyClass.class:1.2-bc1a6b6]
        at com.sk89q.wepif.PermissionsResolverManager.findResolver(PermissionsResolverManager.java:113) [WorldEdit.jar:?]
        at com.sk89q.wepif.PermissionsResolverManager.<init>(PermissionsResolverManager.java:107) [WorldEdit.jar:?]
        at com.sk89q.wepif.PermissionsResolverManager.initialize(PermissionsResolverManager.java:70) [WorldEdit.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:103) [WorldEdit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:172) [JavaPlugin.class:1.2-bc1a6b6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:321) [JavaPluginLoader.class:1.2-bc1a6b6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:397) [SimplePluginManager.class:1.2-bc1a6b6]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:415) [CraftServer.class:1.2-bc1a6b6]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:356) [CraftServer.class:1.2-bc1a6b6]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:436) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:391) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:348) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:601) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: org.anjocaido.groupmanager.permissions.AnjoPermissionsHandler
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[PluginClassLoader.class:1.2-bc1a6b6]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[PluginClassLoader.class:1.2-bc1a6b6]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
        ... 21 more
[01:11:47 INFO]: WEPIF: Using the Bukkit Permissions API.
[01:11:47 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R1 as the Bukkit adapter
`

And CraftBook Error:
`[01:25:33 ERROR]: Could not pass event BlockRedstoneEvent to CraftBook v3.10-SNAPSHOT;4505-8c25911
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.craftbook.bukkit.util.CraftBookBukkitUtil
        at com.sk89q.craftbook.bukkit.MechanicListenerAdapter.handleDirectWireInput(MechanicListenerAdapter.java:341) ~[?:?]
        at com.sk89q.craftbook.bukkit.MechanicListenerAdapter.handleRedstoneForBlock(MechanicListenerAdapter.java:312) ~[?:?]
        at com.sk89q.craftbook.bukkit.MechanicListenerAdapter.onBlockRedstoneChange(MechanicListenerAdapter.java:184) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor279.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:64) ~[EventExecutor$2.class:1.2-bc1a6b6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.2-bc1a6b6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [SimplePluginManager.class:1.2-bc1a6b6]
        at net.minecraft.block.BlockBasePressurePlate.func_180666_a(BlockBasePressurePlate.java:134) [aor.class:?]
        at net.minecraft.block.BlockBasePressurePlate.func_180650_b(BlockBasePressurePlate.java:105) [aor.class:?]
        at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:958) [oo.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:441) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:899) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:803) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:650) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
`

I'm using 456 build

**Comment by ErriourRU** [comment]
And this (FAWE):
`[00:12:18 ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v19.07.12-5cc5ce5-1277-22.3.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:66) ~[EventExecutor$2.class:1.2-bc1a6b6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.2-bc1a6b6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [SimplePluginManager.class:1.2-bc1a6b6]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:804) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(CPacketPlayer.java:33) [lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$Rotation.func_148833_a(CPacketPlayer.java:152) [lk$c.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:860) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:803) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:650) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 76048
        at com.boydti.fawe.FaweCache.getBlock(FaweCache.java:91) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitPlayer.getBlockInHand(BukkitPlayer.java:97) ~[?:?]
        at com.boydti.fawe.wrappers.PlayerWrapper.getBlockInHand(PlayerWrapper.java:68) ~[?:?]
        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:1009) ~[?:?]
        at com.boydti.fawe.bukkit.listener.BrushListener.onPlayerMove(BrushListener.java:73) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor12.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:64) ~[EventExecutor$2.class:1.2-bc1a6b6]
        ... 14 more
`

`
[00:12:18 ERROR]: Could not pass event PlayerItemHeldEvent to FastAsyncWorldEdit v19.07.12-5cc5ce5-1277-22.3.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:66) ~[EventExecutor$2.class:1.2-bc1a6b6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.2-bc1a6b6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [SimplePluginManager.class:1.2-bc1a6b6]
        at net.minecraft.network.NetHandlerPlayServer.func_147355_a(NetHandlerPlayServer.java:1338) [pa.class:?]
        at net.minecraft.network.play.client.CPacketHeldItemChange.func_148833_a(SourceFile:30) [lv.class:?]
        at net.minecraft.network.play.client.CPacketHeldItemChange.func_148833_a(SourceFile:8) [lv.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:860) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:803) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:650) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 76048
        at com.boydti.fawe.FaweCache.getBlock(FaweCache.java:91) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitPlayer.getBlockInHand(BukkitPlayer.java:97) ~[?:?]
        at com.boydti.fawe.wrappers.PlayerWrapper.getBlockInHand(PlayerWrapper.java:68) ~[?:?]
        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:1009) ~[?:?]
        at com.boydti.fawe.bukkit.listener.BrushListener.onPlayerItemHoldEvent(BrushListener.java:38) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor14.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:64) ~[EventExecutor$2.class:1.2-bc1a6b6]
        ... 14 more
`
