### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by CKATEPTb** [PFCraft/Mohist#149]
```
java.lang.NoClassDefFoundError: net/minecraft/world/World$3
    at net.minecraft.world.World.func_190524_a(World.java:733)
    at net.minecraft.world.World.func_175685_c(World.java:661)
    at net.minecraft.world.World.func_175722_b(World.java:608)
    at net.minecraft.world.World.markAndNotifyBlock(World.java:544)
    at net.minecraft.world.World.func_180501_a(World.java:524)
    at net.minecraft.block.BlockBush.func_176475_e(BlockBush.java:71)
    at net.minecraft.block.BlockBush.func_180650_b(BlockBush.java:60)
    at net.minecraft.block.BlockSapling.func_180650_b(BlockSapling.java:60)
    at net.minecraft.block.Block.func_180645_a(Block.java:507)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:692)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:443)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:899)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:803)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:650)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by Mgazul** [comment]
What causes this?

**Comment by Mgazul** [comment]
fixed  https://github.com/PFCraft/Mohist/commit/816a58f3dbef58d68af2740ad9eed68f767cfec1
