### ISSUE TITLE
Mod conflict

### ISSUE THREAD

**Issue by Mgazul** [PFCraft/Mohist#15]
AppleCore and industrialforegoing Cannot be used simultaneously

`java.lang.RuntimeException: FoodStats has a null player field (this field is added by AppleCore at runtime) on player '<unknown>' (class = net.minecraft.util.FoodStats). This likely means that some mod has overloaded FoodStats, which is incompatible with AppleCore.
	at squeek.applecore.asm.Hooks.verifyFoodStats(Hooks.java:53)
	at squeek.applecore.asm.Hooks.needFood(Hooks.java:270)
	at net.minecraft.util.FoodStats.func_75121_c(FoodStats.java)
	at com.buuz135.industrial.proxy.event.MeatFeederTickHandler.onTick(MeatFeederTickHandler.java:66)`

Triggering process: join the void and respawn, causing the server to crash

**Comment by K4N0** [comment]
I know this is old, but i would like to add that recently in 1.12.2 the mod Oversaturation was the cause of my eating and crashing.
