### ISSUE TITLE
UnsupportedOperationException with EnderIO

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#155]
```
java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(AbstractList.java:161)
	at java.util.AbstractList$Itr.remove(AbstractList.java:374)
	at crazypants.enderio.base.item.darksteel.upgrade.direct.DirectUpgrade.doDirect(DirectUpgrade.java:155)
	at crazypants.enderio.base.item.darksteel.upgrade.direct.DirectUpgrade.blockDropEvent(DirectUpgrade.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_252_DirectUpgrade_blockDropEvent_HarvestDropsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:344)
	at net.minecraft.block.Block.func_180653_a(Block.java:576)
	at net.minecraft.block.Block.func_176226_b(Block.java:568)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:188)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:169)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:958)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:441)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:894)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:650)
	at java.lang.Thread.run(Thread.java:813)
```
```
-- Head --
Thread: Server thread
Stacktrace:
	at java.util.AbstractList.remove(AbstractList.java:161)
	at java.util.AbstractList$Itr.remove(AbstractList.java:374)
	at crazypants.enderio.base.item.darksteel.upgrade.direct.DirectUpgrade.doDirect(DirectUpgrade.java:155)
	at crazypants.enderio.base.item.darksteel.upgrade.direct.DirectUpgrade.blockDropEvent(DirectUpgrade.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_252_DirectUpgrade_blockDropEvent_HarvestDropsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:344)
	at net.minecraft.block.Block.func_180653_a(Block.java:576)
	at net.minecraft.block.Block.func_176226_b(Block.java:568)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:188)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:169)

-- Block being ticked --
Details:
	Block: minecraft:flowing_water[level=0]
	Block location: World: (-9831,62,-2139), Chunk: (at 9,3,5 in -615,-134; contains blocks -9840,0,-2144 to -9825,255,-2129), Region: (-20,-5; contains chunks -640,-160 to -609,-129, blocks -10240,0,-2560 to -9729,255,-2049)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:958)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:441)
```

**Comment by Mgazul** [comment]
This appears to be an enderio error that needs further validation
