### ISSUE TITLE
Crash on latest build with RandomPatches

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#157]
```
[10:53:46 ERROR]: Failed to transform class: net.minecraft.network.PacketBuffer
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at com.therandomlabs.randompatches.patch.packetsize.PacketBufferPatch.apply(PacketBufferPatch.java:27) ~[randompatches-1.12.2-1.16.3.1.jar:?]
	at com.therandomlabs.randompatches.core.RPTransformer.transform(RPTransformer.java:37) [randompatches-1.12.2-1.16.3.1.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) [ASMTransformerWrapper$TransformerWrapper.class:1.2-dc20f30]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:946) [?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:891) [?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:874) [?:1.8.0_212]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.registerChannel(FMLNetworkHandler.java:214) [FMLNetworkHandler.class:1.2-dc20f30]
	at net.minecraftforge.fml.common.FMLContainer.modConstruction(FMLContainer.java:92) [FMLContainer.class:1.2-dc20f30]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:1.2-dc20f30]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:1.2-dc20f30]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:1.2-dc20f30]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594) [Loader.class:1.2-dc20f30]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:100) [FMLServerHandler.class:1.2-dc20f30]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:334) [FMLCommonHandler.class:1.2-dc20f30]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:163) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```

**Comment by GDVE** [comment]
You try to delete "libraries" directory?

**Comment by Zilacon** [comment]
This was on a fresh libraries download on the latest version. I always redownload libraries when i update.

**Comment by Mgazul** [comment]
It is not recommended to use randompatches, as some of its modifications have damaged spigot's patches
