### ISSUE TITLE
Crash on latest build with Netty

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#158]
```
[10:53:46 ERROR]: Encountered an unexpected exception
java.lang.VerifyError: JVMVRFY007 final method overridden; class=io/netty/buffer/AdvancedLeakAwareByteBuf, method=release(I)Z
	at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:1.8.0_212]
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:391) ~[?:1.8.0_212]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:360) ~[?:1.8.0_212]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_212]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682) ~[?:1.8.0_212]
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89) ~[?:1.8.0_212]
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086) ~[?:1.8.0_212]
	at java.security.AccessController.doPrivileged(AccessController.java:739) ~[?:1.8.0_212]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589) ~[?:1.8.0_212]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:946) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:891) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:874) ~[?:1.8.0_212]
	at io.netty.buffer.ByteBufUtil.<clinit>(ByteBufUtil.java:84) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.buffer.ByteBufAllocator.<clinit>(ByteBufAllocator.java:24) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:58) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:71) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:183) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:164) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:148) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:135) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:100) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at net.minecraftforge.fml.common.network.FMLEmbeddedChannel.<init>(FMLEmbeddedChannel.java:51) ~[Tekxit.jar:1.2-dc20f30]
	at net.minecraftforge.fml.common.network.NetworkRegistry.newChannel(NetworkRegistry.java:206) ~[Tekxit.jar:1.2-dc20f30]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.registerChannel(FMLNetworkHandler.java:214) ~[Tekxit.jar:1.2-dc20f30]
	at net.minecraftforge.fml.common.FMLContainer.modConstruction(FMLContainer.java:92) ~[Tekxit.jar:1.2-dc20f30]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[Tekxit.jar:1.2-dc20f30]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[Tekxit.jar:1.2-dc20f30]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:1.2-dc20f30]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594) ~[Loader.class:1.2-dc20f30]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:100) ~[FMLServerHandler.class:1.2-dc20f30]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:334) ~[FMLCommonHandler.class:1.2-dc20f30]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:163) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```

**Comment by Zilacon** [comment]
This is still an issue on the latest build @Mgazul @azbh111 
```
[14:29:18 ERROR]: Encountered an unexpected exception
java.lang.VerifyError: JVMVRFY007 final method overridden; class=io/netty/buffer/AdvancedLeakAwareByteBuf, method=release(I)Z
	at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:1.8.0_212]
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:391) ~[?:1.8.0_212]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:360) ~[?:1.8.0_212]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_212]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682) ~[?:1.8.0_212]
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89) ~[?:1.8.0_212]
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086) ~[?:1.8.0_212]
	at java.security.AccessController.doPrivileged(AccessController.java:739) ~[?:1.8.0_212]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589) ~[?:1.8.0_212]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:946) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:891) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:874) ~[?:1.8.0_212]
	at io.netty.buffer.ByteBufUtil.<clinit>(ByteBufUtil.java:84) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.buffer.ByteBufAllocator.<clinit>(ByteBufAllocator.java:24) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:58) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:71) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:183) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:164) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:148) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:135) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:100) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at net.minecraftforge.fml.common.network.FMLEmbeddedChannel.<init>(FMLEmbeddedChannel.java:51) ~[Tekxit.jar:1.2-cbee137]
	at net.minecraftforge.fml.common.network.NetworkRegistry.newChannel(NetworkRegistry.java:206) ~[Tekxit.jar:1.2-cbee137]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.registerChannel(FMLNetworkHandler.java:214) ~[Tekxit.jar:1.2-cbee137]
	at net.minecraftforge.fml.common.FMLContainer.modConstruction(FMLContainer.java:92) ~[Tekxit.jar:1.2-cbee137]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[Tekxit.jar:1.2-cbee137]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[Tekxit.jar:1.2-cbee137]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:1.2-cbee137]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594) ~[Loader.class:1.2-cbee137]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:100) ~[FMLServerHandler.class:1.2-cbee137]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:334) ~[FMLCommonHandler.class:1.2-cbee137]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:163) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```
