### ISSUE TITLE
start crash

### ISSUE THREAD

**Issue by HuaXiY** [PFCraft/Mohist#160]
[22:23:43 ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:67) [bukkit.jar:1.2-db63d4e]
        at red.mohist.Mohist.main(Mohist.java:63) [bukkit.jar:1.2-db63d4e]
Caused by: java.lang.VerifyError: JVMVRFY032 <init> 的接收器错误 类=net/minecraft/entity/player/EntityPlayer，方法=<init>(Lnet/minecraft/world/World;Lcom/mojang/authlib/GameProfile;)V，pc=66
Exception Details:
  Location:
    net/minecraft/entity/player/EntityPlayer.<init>(Lnet/minecraft/world/World;Lcom/mojang/authlib/GameProfile;)V @66: JBinvokespecial
  Reason:
    Type 'net/minecraft/entity/player/EntityPlayer' (current frame, stack[3]) is not assignable to 'uninitializedThis'
  Current Frame:
    bci: @66
    flags: { }
    locals: { 'net/minecraft/entity/player/EntityPlayer', 'net/minecraft/world/World', 'com/mojang/authlib/GameProfile' }
    stack: { 'net/minecraft/entity/player/EntityPlayer', 'uninitialized', 'uninitialized', 'net/minecraft/entity/player/EntityPlayer' }
  Stackmap Table:
    full_frame(@243,{Object[#1],Object[#77],Object[#98]},{Object[#1],Object[#1],Object[#224],Object[#224],Object[#35]})
    full_frame(@244,{Object[#1],Object[#77],Object[#98]},{Object[#1],Object[#1],Object[#224],Object[#224],Object[#35],integer})
        at net.minecraft.util.datafix.DataFixesManager.func_188279_a(DataFixesManager.java:170) ~[rz.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1630) ~[MinecraftServer.class:?]
        ... 12 more
一个问题导致了服务器启动失败
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:67)
        at red.mohist.Mohist.main(Mohist.java:63)
Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
        at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
        at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
        at java.lang.Runtime.exit(Runtime.java:107)
        at java.lang.System.exit(System.java:344)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

**Comment by Mgazul** [comment]
暂时不兼容苹果核

**Comment by GDVE** [comment]
-Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true - try this arguments

**Comment by Mgazul** [comment]
fixed
