### ISSUE TITLE
Quark doesn't work

### ISSUE THREAD

**Issue by ErriourRU** [PFCraft/Mohist#161]
Quark doesn't work on last version (I checked 479, 480, 481)
`[14:53:21 ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/yaml/snakeyaml/error/MarkedYAMLException
        at net.minecraft.server.management.PlayerList.<init>(PlayerList.java:103) ~[pl.class:?]
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:14) ~[ny.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:223) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.error.MarkedYAMLException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
        ... 5 more
Caused by: java.lang.NullPointerException
`
Crash file: [https://pastebin.com/6AxjeHzH](https://pastebin.com/6AxjeHzH)

#456 hasn't this problem.

**Comment by Mgazul** [comment]
Seems to be related to library update, I am checking

**Comment by Mgazul** [comment]
Have you downloaded the library files again?

**Comment by ErriourRU** [comment]
Yes, problem in not removed libraries before update. Thanks!
