### ISSUE TITLE
Many plugins' commands do not work in-game.

### ISSUE THREAD

**Issue by OFWModz** [PFCraft/Mohist#165]
Many plugins such as ClearLagg's commands do not seem to work in game, despite appearing in the /plugins command list.

If I am missing something, please let me know.

The only plugin I got working with commands so far is Vault.

After attemping /plugins reload ClearLag, I got this error:

[22:25:01 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'plugins reload ClearLag' in org.bukkit.command.defaults.PluginsCommand(plugins)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[SimpleCommandMap.class:1.2-5a1e180]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:688) ~[CraftServer.class:1.2-5a1e180]
        at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:1570) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:1417) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:51) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:12) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
        at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:858) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:449) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:801) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) ~[SimplePluginManager.class:1.2-5a1e180]
        at red.mohist.pluginmanager.Control.enablePlugin(Control.java:63) ~[Control.class:1.2-5a1e180]
        at red.mohist.pluginmanager.PluginManagers.reloadPluginCommand(PluginManagers.java:147) ~[PluginManagers.class:1.2-5a1e180]
        at org.bukkit.command.defaults.PluginsCommand.execute(PluginsCommand.java:44) ~[PluginsCommand.class:1.2-5a1e180]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) ~[SimpleCommandMap.class:1.2-5a1e180]
        ... 14 more

Futher info:
[22:35:42 WARN]: Caused by: java.lang.IllegalStateException: Initial initialization
[22:35:42 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:154)
[22:35:42 WARN]:        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:51)
[22:35:42 WARN]:        at me.minebuilders.clearlag.Clearlag.<init>(Clearlag.java:14)
[22:35:42 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:35:42 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[22:35:42 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[22:35:42 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[22:35:42 WARN]:        at java.lang.Class.newInstance(Unknown Source)
[22:35:42 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:85)
[22:35:42 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[22:35:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334)
[22:35:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255)
[22:35:42 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:334)
[22:35:42 WARN]:        at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:442)
[22:35:42 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:308)
[22:35:42 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:307)
[22:35:42 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:599)
[22:35:42 WARN]:        ... 1 more

**Comment by Mgazul** [comment]
Plugins reload errors are normal, and not all plug-ins support hot loading and reloading.

**Comment by OFWModz** [comment]
They do not function in the first place, hence me attempting so.
