### ISSUE TITLE
Extra Utilities 2 Crash

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#167]
Ive gotten this crash on my server over a dozen times now.

```
[01:31:48 ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world entities
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:912) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:460) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:799) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:651) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IndexOutOfBoundsException: Index: 338, Size: 338
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_212]
	at java.util.ArrayList.remove(ArrayList.java:496) ~[?:1.8.0_212]
	at net.minecraft.world.World.func_72939_s(World.java:2096) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:835) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:906) ~[MinecraftServer.class:?]
	... 4 more
```

Crash report: 
[crash-2019-08-04_01.31.48-server.txt](https://github.com/PFCraft/Mohist/files/3464692/crash-2019-08-04_01.31.48-server.txt)

**Comment by Mgazul** [comment]
The first one should be fixed
