### ISSUE TITLE
Permissions.yml Is Broken, Can Mine But Can't Even Use /help Without OP

### ISSUE THREAD

**Issue by OFWModz** [PFCraft/Mohist#170]
Running the latest release of Mohist from codeMC (Latest successful build: Mohist-809b10e-server), and upon running no players without OP can use any commands what-so-ever, I have posted on bukkit about it but it seems no one has faced this before (https://bukkit.org/threads/weird-permissions-yml-issue-in-mohist-craftbukkit-paper-spigot.480454/) - It states that the permission "groups" and "users" are already defined., meaning my working permissions.yml (Viewable on the forum post) does nothing. I'm unsure but it seems to be an issue with mohist. Can someone look into this? It's broke my server entirely atm.

For info, I am running no permissions plugins, but have tried multiple, all cannot apply permissions either (using minecraft.command.help as a test).

**Comment by Mgazul** [comment]
https://github.com/PFCraft/Mohist/commit/c01d50069cd3b2f70187b71db796197aea522462
This may help you. We changed the permission registration mechanism

**Comment by OFWModz** [comment]
[16:15:44 ERROR]: Permission in permissions.yml was already defined
java.lang.IllegalArgumentException: The permission groups is already defined!
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:593) ~[SimplePluginManager.class:911dff2]
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:586) ~[SimplePluginManager.class:911dff2]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadCustomPermissions(CraftServer.java:840) [CraftServer.class:911dff2]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:424) [CraftServer.class:911dff2]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:445) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:400) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:357) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:610) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[16:15:44 ERROR]: Permission in permissions.yml was already defined
java.lang.IllegalArgumentException: The permission users is already defined!
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:593) ~[SimplePluginManager.class:911dff2]
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:586) ~[SimplePluginManager.class:911dff2]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadCustomPermissions(CraftServer.java:840) [CraftServer.class:911dff2]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:424) [CraftServer.class:911dff2]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:445) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:400) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:357) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:610) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

Is my permissions.yml structure wrong? 
[permissions.txt](https://github.com/PFCraft/Mohist/files/3477948/permissions.txt)
(Only .txt to upload here)

**Comment by OFWModz** [comment]
This is still an issue. Could you provide a template working permissions file?
