### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by ErriourRU** [PFCraft/Mohist#171]
Is it problem of core or mods?

```
WARNING: coremods are present:
  LoadingPlugin ([CatFix]Quark-r1.5-146.jar)
  EventHelperCoreMod (EventHelper-1.12.2-2.6.2.jar)
Contact their authors BEFORE contacting forge


Time: 08.08.19 9:25
Description: Ticking entity

java.util.ConcurrentModificationException
	at net.minecraft.world.World$1.guard(World.java:128)
	at net.minecraft.world.World$1.remove(World.java:120)
	at net.minecraft.entity.Entity.teleportTo(Entity.java:2875)
	at net.minecraft.entity.Entity.changeDimension(Entity.java:2857)
	at net.minecraft.entity.item.EntityItem.changeDimension(EntityItem.java:503)
	at net.minecraft.entity.Entity.func_184204_a(Entity.java:2802)
	at net.minecraft.entity.Entity.postTick(Entity.java:476)
	at net.minecraft.world.World.func_72866_a(World.java:2405)
	at net.minecraft.world.World.func_72870_g(World.java:2348)
	at net.minecraft.world.World.func_72939_s(World.java:2119)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:835)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:918)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:460)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:807)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Flashback083** [comment]
try to remove quark

**Comment by Mgazul** [comment]
Latest build? I have already fixed this problem

**Comment by ErriourRU** [comment]
No, 530 was. I updated to 536. Will check again...
