### ISSUE TITLE
More crashes for god of crashes!

### ISSUE THREAD

**Issue by ErriourRU** [PFCraft/Mohist#172]
And after fix #171 new crash appears. Build 543.
This happens when you enter the portal to nether.
```
Time: 09.08.19 8:54
Description: Exception ticking world entities

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:850)
	at net.minecraft.world.World.func_72939_s(World.java:2064)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:841)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:918)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:464)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:807)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Zilacon** [comment]
I also have this crash.

**Comment by Mgazul** [comment]
# 546

**Comment by Zilacon** [comment]
Still getting this crash on latest build.
```
[11:34:22 ERROR]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@135dc1f5:
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_212]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_212]
	at org.silvercatcher.reforged.ReforgedEvents.onWorldTick(ReforgedEvents.java:113) ~[ReforgedEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_917_ReforgedEvents_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:4f151dc]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) [EventBus.class:4f151dc]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:4f151dc]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:927) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:464) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:807) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```

**Comment by ErriourRU** [comment]
No more problems found since fix, so that closed.
