### ISSUE TITLE
ConcurrentModificationException with LagAssist plugin

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#178]
```
[12:15:07 WARN]: [LagAssist] Task #5 for LagAssist v2.18.1 generated an exception
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_212]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_212]
	at cx.sfy.LagAssist.stacker.StackMonitor.lambda$0(StackMonitor.java:35) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:73) ~[CraftTask.class:7fa1ba5]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:426) [CraftScheduler.class:7fa1ba5]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:861) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:807) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Zilacon** [comment]
Similar but different from https://github.com/PFCraft/Mohist/issues/138
