### ISSUE TITLE
Server Crash with java.lang.IllegalArgumentException: Cannot set property PropertyInteger

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#179]
```
java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} to 18 on block minecraft:fire, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227)
	at net.minecraft.block.BlockFire.func_176203_a(BlockFire.java:528)
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:210)
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:193)
	at net.minecraft.block.BlockFire.func_180650_b(BlockFire.java:255)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:964)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:445)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:907)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:807)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
	at java.lang.Thread.run(Thread.java:813)
```
Crash Log:
[crash-2019-08-13_15.29.59-server.txt](https://github.com/PFCraft/Mohist/files/3499144/crash-2019-08-13_15.29.59-server.txt)

**Comment by Mgazul** [comment]
Not sure what went wrong

**Comment by Zilacon** [comment]
Basically if you set anything on fire on the server, it crashes with that error.

**Comment by Mgazul** [comment]
My tests did not find this error

**Comment by braddevans** [comment]
lemme do a quick test
