### ISSUE TITLE
world Difficulty causing startup crash

### ISSUE THREAD

**Issue by megoesrawr** [PFCraft/Mohist#18]
Error:
`java.lang.NullPointerException
    at net.minecraft.world.storage.WorldInfo.setDifficulty(WorldInfo.java:737)
    at net.minecraft.server.MinecraftServer.setDifficultyForAllWorlds(MinecraftServer.java:1214)
    at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:396)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:297)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648)
    at java.lang.Thread.run(Unknown Source)`

**Comment by megoesrawr** [comment]
nvm something with twilight forest. :/

**Comment by Mgazul** [comment]
Need more detailed information；
I tried to install twilight forest and didn't have your problem.

**Comment by megoesrawr** [comment]
im using the newest mohist and https://minecraft.curseforge.com/projects/roguelike-adventures-and-dungeons minus the dimensionaldoors
