### ISSUE TITLE
ConcurrentModificationException after update to Mohist-dd20ed3

### ISSUE THREAD

**Issue by BlayzerQ** [PFCraft/Mohist#181]
After update to Mohist-dd20ed3 from Mohist-1.0-faaaa38, server crash when player call /home command (on Mohist-1.0-faaaa38 all is ok)
[crash-2019-08-15_17.48.40-server.txt](https://github.com/PFCraft/Mohist/files/3506131/crash-2019-08-15_17.48.40-server.txt)

**Comment by BlayzerQ** [comment]
Why?

**Comment by Mgazul** [comment]
fixed

**Comment by BlayzerQ** [comment]
When loggin on Mohist-e559f72-server, console flood-crash:
`java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at net.minecraft.world.World.func_72907_a(World.java:3512)
	at forestry.lepidopterology.entities.AIButterflyMate.canInteract(AIButterflyMate.java:41)
	at forestry.lepidopterology.entities.AIButterflyInteract.func_75250_a(AIButterflyInteract.java:40)
	at forestry.lepidopterology.entities.AIButterflyMate.func_75250_a(AIButterflyMate.java:76)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:810)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2689)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:610)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2510)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:319)
	at forestry.lepidopterology.entities.EntityButterfly.func_70071_h_(EntityButterfly.java:457)
	at net.minecraft.world.World.func_72866_a(World.java:2355)
	at net.minecraft.world.World.func_72870_g(World.java:2299)
	at net.minecraft.world.World.func_72939_s(World.java:2071)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:841)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:918)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:807)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
	at java.lang.Thread.run(Thread.java:748)`
And server crash with:
`java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
	at net.minecraft.entity.EntityTracker.func_85172_a(EntityTracker.java:397)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:159)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:202)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:449)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:907)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:807)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
	at java.lang.Thread.run(Thread.java:748)`
