### ISSUE TITLE
Crash at server start

### ISSUE THREAD

**Issue by AlexCreeper25** [PFCraft/Mohist#183]
Got this crash error when starting server. The error doesn't even generate any crash-report. The only thing I see is this log I'm going to leave below:

`[17:35:18] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at red.mohist.Mohist.main(Mohist.java:97) [server.jar:8ad1c45]
Caused by: java.lang.NoClassDefFoundError: org/yaml/snakeyaml/error/YAMLException
	at red.mohist.configuration.ConfigBase.<init>(ConfigBase.java:33) ~[ConfigBase.class:8ad1c45]
	at red.mohist.configuration.MohistConfig.<init>(MohistConfig.java:60) ~[MohistConfig.class:8ad1c45]
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:185) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:75) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1648) ~[MinecraftServer.class:?]
	... 11 more
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.error.YAMLException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	at red.mohist.configuration.ConfigBase.<init>(ConfigBase.java:33) ~[ConfigBase.class:8ad1c45]
	at red.mohist.configuration.MohistConfig.<init>(MohistConfig.java:60) ~[MohistConfig.class:8ad1c45]
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:185) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:75) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1648) ~[MinecraftServer.class:?]
	... 11 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	at red.mohist.configuration.ConfigBase.<init>(ConfigBase.java:33) ~[ConfigBase.class:8ad1c45]
	at red.mohist.configuration.MohistConfig.<init>(MohistConfig.java:60) ~[MohistConfig.class:8ad1c45]
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:185) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:75) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1648) ~[MinecraftServer.class:?]
	... 11 more
`

**Comment by Mgazul** [comment]
fixed

**Comment by AlexCreeper25** [comment]
Alright i’ll try it ASAP

**Comment by AlexCreeper25** [comment]
Just tried with the new build, and i get the same error. I'll leave the full log so that you may be able to see if there are any incompatible mods. No Spigot/Sponge plugins are installed.

[latest.log](https://github.com/PFCraft/Mohist/files/3512503/latest.log)

**Comment by Mgazul** [comment]
Is the library file complete? Try deleting and redownloading

**Comment by AlexCreeper25** [comment]
Do i have to download the default forge libraries or is there a specific library set?

**Comment by Mgazul** [comment]
https://github.com/PFCraft/Mohist/releases/download/libraries-1.2/libraries-1.2.zip

**Comment by AlexCreeper25** [comment]
Still not working... Tho this time i get this error:

`Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/yaml/snakeyaml/error/MarkedYAMLException
	at net.minecraft.server.management.PlayerList.<init>(PlayerList.java:106)
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:17)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:193)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:639)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.error.MarkedYAMLException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
Caused by: java.lang.NullPointerException
`
