### ISSUE TITLE
Crash with WorldControl mod 

### ISSUE THREAD

**Issue by ErriourRU** [PFCraft/Mohist#184]
When I'm turning on information panel:
```
Time: 18.08.19 2:49
Description: Ticking block entity

java.lang.AbstractMethodError: worldcontrolteam.worldcontrol.items.ItemFluidCard.getStringData(Ljava/util/List;ILnet/minecraft/item/ItemStack;Z)Ljava/util/List;
	at worldcontrolteam.worldcontrol.api.screen.predefs.ScreenElementProviderCard.onCardUpdate(ScreenElementProviderCard.java:36)
	at worldcontrolteam.worldcontrol.tileentity.TileEntityInfoPanel.func_73660_a(TileEntityInfoPanel.java:484)
	at net.minecraft.world.World.func_72939_s(World.java:2174)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:850)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:924)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:663)
	at java.lang.Thread.run(Thread.java:748)
```

After restart panel stays turned on.
Core version: #573
Mod version: 1.0.31

**Comment by Mgazul** [comment]
This is not a mohist issue, mod says @sideonly (side.client) in the code, indicating that this is only available on the CLIENT Side
