### ISSUE TITLE
ConcurrentModificationException crash with Mohist

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#190]
```
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
    at net.minecraft.entity.EntityTracker.sendLeashedEntitiesInChunk(EntityTracker.java:397)
    at net.minecraft.server.management.PlayerChunkMapEntry.sendToPlayers(PlayerChunkMapEntry.java:159)
    at net.minecraft.server.management.PlayerChunkMap.tick(PlayerChunkMap.java:202)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:454)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:914)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:462)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:812)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:664)
    at java.lang.Thread.run(Thread.java:813)
```

**Comment by Zilacon** [comment]
Server WILL NOT stay online longer then 5 minutes with crash.

**Comment by Mgazul** [comment]
When does this error occur

**Comment by Zilacon** [comment]
Randomly or right after the server starts, Heres all  my crash reports for just a couple hours:
[crash-2019-08-22_18.03.48-server.txt](https://github.com/PFCraft/Mohist/files/3532596/crash-2019-08-22_18.03.48-server.txt)
[crash-2019-08-22_18.09.18-server.txt](https://github.com/PFCraft/Mohist/files/3532597/crash-2019-08-22_18.09.18-server.txt)
[crash-2019-08-22_18.26.38-server.txt](https://github.com/PFCraft/Mohist/files/3532598/crash-2019-08-22_18.26.38-server.txt)
[crash-2019-08-22_18.38.49-server.txt](https://github.com/PFCraft/Mohist/files/3532599/crash-2019-08-22_18.38.49-server.txt)
[crash-2019-08-22_18.51.46-server.txt](https://github.com/PFCraft/Mohist/files/3532600/crash-2019-08-22_18.51.46-server.txt)
[crash-2019-08-22_18.56.10-server.txt](https://github.com/PFCraft/Mohist/files/3532601/crash-2019-08-22_18.56.10-server.txt)
[crash-2019-08-22_19.11.59-server.txt](https://github.com/PFCraft/Mohist/files/3532602/crash-2019-08-22_19.11.59-server.txt)
[crash-2019-08-22_17.22.01-server.txt](https://github.com/PFCraft/Mohist/files/3532603/crash-2019-08-22_17.22.01-server.txt)
[crash-2019-08-22_17.28.16-server.txt](https://github.com/PFCraft/Mohist/files/3532604/crash-2019-08-22_17.28.16-server.txt)
[crash-2019-08-22_17.33.46-server.txt](https://github.com/PFCraft/Mohist/files/3532605/crash-2019-08-22_17.33.46-server.txt)
[crash-2019-08-22_17.38.27-server.txt](https://github.com/PFCraft/Mohist/files/3532606/crash-2019-08-22_17.38.27-server.txt)
[crash-2019-08-22_17.48.18-server.txt](https://github.com/PFCraft/Mohist/files/3532607/crash-2019-08-22_17.48.18-server.txt)

@Mgazul

**Comment by Zilacon** [comment]
A player from my server  said the server crashes when they try to crasft anything.

Mr_Randomer.
8/22/2019, 8:56:15 PM
Me and Jared are just playing through the crashes ahaha everytime were about to craft something it crashes, i thought at first there was something wrong with the quarry, as i have seen that quarrys crash other servers

**Comment by Mgazul** [comment]
Testing the latest version

**Comment by Zilacon** [comment]
@Mgazul Tested latest version, same exact crash.

**Comment by Zilacon** [comment]
Got rid of a lot of old world data and now i got a new crash:
```
Description: Exception in server tick loop

java.lang.NullPointerException
    at net.minecraft.world.gen.ChunkProviderServer.handler$onSaveChunks$zzo000(ChunkProviderServer.java:532)
    at net.minecraft.world.gen.ChunkProviderServer.saveChunks(ChunkProviderServer.java)
    at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1282)
    at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:465)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:834)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:664)
    at java.lang.Thread.run(Thread.java:813)
```

**Comment by Zilacon** [comment]
@Mgazul Disabled BetterFPS and FoamFix and now im getting this error:
```
[05:35:08 ERROR]: Failed to save chunk
 java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:32) ~[fy.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:118) ~[gi.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:108) ~[gi.class:?]
	at net.minecraft.world.chunk.storage.RegionFileCache.getChunkOutputStream(RegionFileCache.java:139) ~[ayk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_183013_b(AnvilChunkLoader.java:244) ~[aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:220) [aye.class:?]
	at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(ThreadedFileIOBase.java:42) [bgx.class:?]
	at net.minecraft.world.storage.ThreadedFileIOBase.run(ThreadedFileIOBase.java:31) [bgx.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```
