### ISSUE TITLE
plugin supports

### ISSUE THREAD

**Issue by Cronosus** [PFCraft/Mohist#21]
hi again, some problems with plugins and i think it must be resolved here

MySkin say this: https://paste.ee/p/qYRcu
https://www.spigotmc.org/resources/myskin-1-8-1-14-1.52303/

ProtocolLib have this problem: https://paste.ee/p/NlNto
https://www.spigotmc.org/resources/protocollib.1997/

**Comment by Mgazul** [comment]
Please use the latest version of Mohist, you are using the old version ( 14.23.5.2837-0.0.8a)

**Comment by Mgazul** [comment]
https://ci.codemc.org/job/PFCraft/job/Mohist/

**Comment by Cronosus** [comment]
same errors even with latest mohist....

**Comment by Cronosus** [comment]
ad. but looks like with you latest build from jenkins it started working 👍 
except myskin give this
`[09:43:40 WARN]: [MySkin] Task #40 for MySkin v2.7 generated an exception
java.lang.NullPointerException: null
        at eu.blackfire62.myskin.bukkit.skinhandler.SkinHandler_v1_12_R1.lambda$update$0(SkinHandler_v1_12_R1.java:109) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:0.0.9-d1d3ffb]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:420) [CraftScheduler.class:0.0.9-d1d3ffb]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:888) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:437) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:839) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:697) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

**Comment by Mgazul** [comment]
You are still using the old version (0.0.8b)，The latest version is 0.0.9-d1d3ffb

**Comment by Mgazul** [comment]
MySkin's error is about to be resolved
