### ISSUE TITLE
Error executing task

### ISSUE THREAD

**Issue by GDVE** [PFCraft/Mohist#23]
This is error on last version 0.0.9 beta

[14:47:34 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 41, Size: 0
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:895) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:437) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:839) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:697) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IndexOutOfBoundsException: Index: 41, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_191]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_191]
        at net.minecraft.inventory.Container.func_75139_a(Container.java:206) ~[afr.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1912) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

https://pastebin.com/6JHSKiLb

**Comment by Mgazul** [comment]
Are you opening a inventory?

**Comment by Mgazul** [comment]
I tried to fix it 1 minute ago and you can test again if an error will occur.

**Comment by GDVE** [comment]
I do nothing, there are a lot of players on the server, most likely someone is interacting with the wrong inventory.
