### ISSUE TITLE
Error when reloading Holographic Displays

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#30]
```> hd
[18:21:25 INFO]: Server is running Holographic Displays v2.3.2 by filoghost
[18:21:25 INFO]: Commands: /hd help
> hd reload
[18:36:16 WARN]: [HolographicDisplays] Unable to get a stack trace element, please inform the developer. You will only see this error once and a fallback method will be used.
java.lang.NoSuchMethodException: java.lang.Throwable.getStackTraceDepth()
	at java.lang.Class.newNoSuchMethodException(Class.java:562) ~[?:1.8.0_212]
	at java.lang.Class.throwExceptionOrReturnNull(Class.java:1195) ~[?:1.8.0_212]
	at java.lang.Class.getMethodHelper(Class.java:1259) ~[?:1.8.0_212]
	at java.lang.Class.getDeclaredMethod(Class.java:931) ~[?:1.8.0_212]
	at red.mohist.remapnms.ReflectionMethods.getDeclaredMethod(ReflectionMethods.java:43) ~[ReflectionMethods.class:0.0.9-bd9cc27]
	at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.init(ReflectMethod.java:36) ~[HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.invoke(ReflectMethod.java:42) ~[HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectionUtils.getStackTraceElement(ReflectionUtils.java:58) [HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.EntityNMSArmorStand.func_145782_y(EntityNMSArmorStand.java:155) [HolographicDisplays.jar:?]
	at net.minecraft.network.play.server.SPacketEntityTeleport.<init>(SourceFile:22) [kt.class:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.EntityNMSArmorStand.setLocationNMS(EntityNMSArmorStand.java:220) [HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:100) [HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:104) [HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:314) [HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:261) [HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.commands.main.subs.ReloadCommand.execute(ReloadCommand.java:95) [HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.commands.main.HologramsCommandHandler.onCommand(HologramsCommandHandler.java:107) [HolographicDisplays.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:0.0.9-bd9cc27]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) [SimpleCommandMap.class:0.0.9-bd9cc27]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:684) [CraftServer.class:0.0.9-bd9cc27]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:670) [CraftServer.class:0.0.9-bd9cc27]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:479) [nz.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:438) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:772) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
[18:36:16 INFO]: Configuration reloaded successfully in 382ms!
```

**Comment by Mgazul** [comment]
> hd
[15:20:10 INFO]: Server is running Holographic Displays v2.3.2 by filoghost
[15:20:10 INFO]: Commands: /hd help
> hd reload
[15:20:12 INFO]: Configuration reloaded successfully in 7ms!
> hd reload
[15:20:14 INFO]: Configuration reloaded successfully in 2ms!
> hd reload
[15:20:14 INFO]: Configuration reloaded successfully in 4ms!
> hd reload
[15:20:15 INFO]: Configuration reloaded successfully in 3ms!

Unable to trigger your question, need more information

**Comment by Zilacon** [comment]
Are you using OpenJ9?

**Comment by Mgazul** [comment]
no

**Comment by Zilacon** [comment]
Can you try it with that?

**Comment by azbh111** [comment]
#84
