### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by GDVE** [PFCraft/Mohist#52]
// Don't be sad, have a hug! <3

Time: 6/27/19 5:38 PM
Description: Exception ticking world

java.lang.NoSuchFieldError: field_82172_bs
	at net.minecraft.entity.EntityLiving.func_98053_h(EntityLiving.java:1247)
	at net.minecraft.entity.monster.EntityZombie.func_180482_a(EntityZombie.java:464)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:201)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:897)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:449)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Mgazul** [comment]
fixed
