### ISSUE TITLE
Cannot teleport to worlds: ChunkNibbleArrays should be 2048 bytes not: 0 [High Priority]

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#82]
```
[02:50:47] [Server thread/INFO]: Zilacon issued server command: /mw move zilacon spawn
[02:50:47] [Server thread/WARN]: Could not set level chunk heightmap, array length is 0 instead of 256
[02:50:47] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mw' in plugin MultiWorld v5.2.8
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.2-087d4b8]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) ~[SimpleCommandMap.class:1.2-087d4b8]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:691) ~[CraftServer.class:1.2-087d4b8]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1570) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1417) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:51) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:12) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:449) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
	at net.minecraft.world.chunk.NibbleArray.<init>(SourceFile:16) ~[axs.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:447) ~[aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:125) ~[aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:89) ~[aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70) ~[ChunkIOProvider.class:1.2-087d4b8]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92) ~[ChunkIOExecutor.class:1.2-087d4b8]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:127) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:98) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:144) ~[on.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:363) ~[CraftWorld.class:1.2-087d4b8]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:867) ~[CraftWorld.class:1.2-087d4b8]
	at multiworld.data.PlayerHandler.movePlayer(PlayerHandler.java:76) ~[?:?]
	at multiworld.command.move.MoveCommand.runCommand(MoveCommand.java:83) ~[?:?]
	at multiworld.command.Command.excute(Command.java:55) ~[?:?]
	at multiworld.command.CommandMap.parseCommand(CommandMap.java:37) ~[?:?]
	at multiworld.command.CommandMap.runCommand(CommandMap.java:67) ~[?:?]
	at multiworld.command.Command.excute(Command.java:55) ~[?:?]
	at multiworld.MultiWorldPlugin.pushCommandStack(MultiWorldPlugin.java:221) ~[?:?]
	at multiworld.MultiWorldPlugin.onCommand(MultiWorldPlugin.java:206) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.2-087d4b8]
	... 15 more
```

```
[02:51:35] [Server thread/WARN]: Could not set level chunk heightmap, array length is 0 instead of 256
[02:51:35] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@fb7b0950:
java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
	at net.minecraft.world.chunk.NibbleArray.<init>(SourceFile:16) ~[axs.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:447) ~[aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:125) ~[aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:89) ~[aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70) ~[ChunkIOProvider.class:1.2-087d4b8]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92) ~[ChunkIOExecutor.class:1.2-087d4b8]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:127) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:98) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:144) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:453) ~[amu.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:448) ~[amu.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:1137) ~[amu.class:?]
	at cofh.cofhworld.world.generator.WorldGen.canGenerateInBlock(WorldGen.java:50) ~[WorldGen.class:?]
	at cofh.cofhworld.world.generator.WorldGen.canGenerateInBlock(WorldGen.java:41) ~[WorldGen.class:?]
	at cofh.cofhworld.world.generator.WorldGen.generateBlock(WorldGen.java:66) ~[WorldGen.class:?]
	at cofh.cofhworld.world.generator.WorldGenMinableCluster.func_180709_b(WorldGenMinableCluster.java:129) ~[WorldGenMinableCluster.class:?]
	at cofh.cofhworld.world.distribution.DistributionUniform.generateFeature(DistributionUniform.java:49) ~[DistributionUniform.class:?]
	at cofh.cofhworld.world.distribution.Distribution.generateFeature(Distribution.java:110) ~[Distribution.class:?]
	at cofh.cofhworld.init.WorldHandler.generateWorld(WorldHandler.java:349) ~[WorldHandler.class:?]
	at cofh.cofhworld.init.WorldTickHandler.tickEnd(WorldTickHandler.java:55) ~[WorldTickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_585_WorldTickHandler_tickEnd_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:1.2-087d4b8]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) [EventBus.class:1.2-087d4b8]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:275) [FMLCommonHandler.class:1.2-087d4b8]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:449) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
[02:51:35] [Server thread/ERROR]: Index: 8 Listeners:
[02:51:35] [Server thread/ERROR]: 0: NORMAL
[02:51:35] [Server thread/ERROR]: 1: ASM: class vazkii.botania.common.core.handler.CommonTickHandler onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 2: ASM: class crazypants.enderio.base.material.material.MaterialCraftingHandler onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 3: ASM: class com.wynprice.secretroomsmod.handler.EnergizedPasteHandler onEntityTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 4: ASM: atomicstryker.battletowers.common.ServerTickHandler@3ac7e6e5 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 5: ASM: INSTANCE onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 6: ASM: INSTANCE tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 7: ASM: INSTANCE onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 8: ASM: cofh.cofhworld.init.WorldTickHandler@881e1666 tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 9: ASM: ic2.core.util.events.TickEventHandler@5d979a26 onWorldTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 10: ASM: micdoodle8.mods.galacticraft.planets.venus.event.EventHandlerVenus@aac229a4 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 11: ASM: com.buuz135.industrial.proxy.event.WorldTickHandler@7aceb6f4 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 12: ASM: atomicstryker.infernalmobs.common.InfernalMobsCore@303871be onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 13: ASM: openmods.world.DelayedActionTickHandler@7702fdb3 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 14: ASM: DISTRIBUTION tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 15: ASM: mods.railcraft.common.blocks.machine.wayobjects.signals.TokenManager@dd7ab4e6 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 16: ASM: mods.railcraft.common.carts.Train$1@7d776940 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 17: ASM: org.silvercatcher.reforged.ReforgedEvents@29b8e731 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 18: ASM: cofh.thermaldynamics.util.TickHandler@2ba19c59 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 19: ASM: vazkii.botania.common.item.ItemGrassSeeds@ab3c2ee6 onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 20: ASM: vazkii.botania.common.item.equipment.tool.terrasteel.ItemTerraAxe@26ffeff7 onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 21: ASM: micdoodle8.mods.galacticraft.planets.asteroids.tick.AsteroidsTickHandlerServer@8348b8d4 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 22: ASM: com.creativemd.littletiles.common.events.LittleDoorHandler@10fbf3b5 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 23: ASM: com.progwml6.natura.world.worldgen.retrogen.TickHandlerWorldRetrogen@c653fad1 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 24: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@49d0e75c serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 25: ASM: micdoodle8.mods.galacticraft.core.tick.TickHandlerServer@1004c8fc onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[02:51:35] [Server thread/ERROR]: 26: ASM: Block{minecraft:air} tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[02:51:35] [Server thread/ERROR]: 27: ASM: ivorius.reccomplex.events.handlers.RCForgeEventHandler@f4f6c7 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[02:51:35] [Server thread/ERROR]: 28: ASM: appeng.hooks.TickHandler@b1b48c5 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[02:51:35] [Server thread/ERROR]: 29: ASM: com.creativemd.creativecore.common.event.CreativeTickHandler@5f55aeae onEventTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[02:51:35] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
	at net.minecraft.world.chunk.NibbleArray.<init>(SourceFile:16) ~[axs.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:447) ~[aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:125) ~[aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:89) ~[aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70) ~[ChunkIOProvider.class:1.2-087d4b8]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92) ~[ChunkIOExecutor.class:1.2-087d4b8]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:127) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:98) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:144) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:453) ~[amu.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:448) ~[amu.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:1137) ~[amu.class:?]
	at cofh.cofhworld.world.generator.WorldGen.canGenerateInBlock(WorldGen.java:50) ~[WorldGen.class:?]
	at cofh.cofhworld.world.generator.WorldGen.canGenerateInBlock(WorldGen.java:41) ~[WorldGen.class:?]
	at cofh.cofhworld.world.generator.WorldGen.generateBlock(WorldGen.java:66) ~[WorldGen.class:?]
	at cofh.cofhworld.world.generator.WorldGenMinableCluster.func_180709_b(WorldGenMinableCluster.java:129) ~[WorldGenMinableCluster.class:?]
	at cofh.cofhworld.world.distribution.DistributionUniform.generateFeature(DistributionUniform.java:49) ~[DistributionUniform.class:?]
	at cofh.cofhworld.world.distribution.Distribution.generateFeature(Distribution.java:110) ~[Distribution.class:?]
	at cofh.cofhworld.init.WorldHandler.generateWorld(WorldHandler.java:349) ~[WorldHandler.class:?]
	at cofh.cofhworld.init.WorldTickHandler.tickEnd(WorldTickHandler.java:55) ~[WorldTickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_585_WorldTickHandler_tickEnd_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:1.2-087d4b8]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) ~[EventBus.class:1.2-087d4b8]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:275) ~[FMLCommonHandler.class:1.2-087d4b8]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:449) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```

**Comment by Zilacon** [comment]
This also caused a crash, apparently from COFH World.

**Comment by Zilacon** [comment]
Fixed it, corrupted world data i guess?
