### ISSUE TITLE
Holographic Displays not visible. [Please fix!]

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#84]
When i do /hd list it shows there are many holo displays in the world im in, but none of them are visible.

**Comment by Zilacon** [comment]
Can someone please fix this?

**Comment by Mgazul** [comment]
Remap an error waiting to be fixed

**Comment by azbh111** [comment]
I test holographicdisplays on the latest build. It work fine

**Comment by Zilacon** [comment]
Can you tell me what magic your using to JOIN or even USE the latest version?
Because it completely deadlocks at start up for me. I cant join, do commands, or even shutdown the server.

**Comment by azbh111** [comment]
View the Server thread stack with [jstack](https://docs.oracle.com/javase/7/docs/technotes/tools/share/jstack.html)

**Comment by Zilacon** [comment]
@azbh111 IDK about jstack but ive posted logs in #94

**Comment by Zilacon** [comment]
Errors from recent build #363:
```
[06:09:08] [Server thread/WARN]: [HolographicDisplays] Task #22 for HolographicDisplays v2.3.2 generated an exception
java.lang.NoSuchMethodError: net/minecraft/entity/item/EntityArmorStand.setNoGravity(Z)V (loaded from jar:file:/root/Desktop/Servers/Tekxit/minecraft_server.1.12.2.jar!/abz.class by net.minecraft.launchwrapper.LaunchClassLoader@f2999d1c) called from class com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.EntityNMSArmorStand (loaded from file:/root/Desktop/Servers/Tekxit/plugins/HolographicDisplays.jar by org.bukkit.plugin.java.PluginClassLoader@4628eed3).
	at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.EntityNMSArmorStand.<init>(EntityNMSArmorStand.java:50) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:99) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:104) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:314) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:261) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.task.StartupLoadHologramsTask.run(StartupLoadHologramsTask.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:73) ~[CraftTask.class:1.2-822dad7]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:426) [CraftScheduler.class:1.2-822dad7]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:453) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```
```
[06:12:51] [Server thread/INFO]: Zilacon issued server command: /hd list
[06:13:07] [Server thread/INFO]: Zilacon issued server command: /hd reload
[06:13:07] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hd' in plugin HolographicDisplays v2.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.2-822dad7]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:133) ~[SimpleCommandMap.class:1.2-822dad7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:668) ~[CraftServer.class:1.2-822dad7]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1570) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1417) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:51) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:12) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:453) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: net/minecraft/entity/item/EntityArmorStand.setNoGravity(Z)V (loaded from jar:file:/root/Desktop/Servers/Tekxit/minecraft_server.1.12.2.jar!/abz.class by net.minecraft.launchwrapper.LaunchClassLoader@f2999d1c) called from class com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.EntityNMSArmorStand (loaded from file:/root/Desktop/Servers/Tekxit/plugins/HolographicDisplays.jar by org.bukkit.plugin.java.PluginClassLoader@4628eed3).
	at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.EntityNMSArmorStand.<init>(EntityNMSArmorStand.java:50) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:99) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:104) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:314) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:261) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.commands.main.subs.ReloadCommand.execute(ReloadCommand.java:95) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.commands.main.HologramsCommandHandler.onCommand(HologramsCommandHandler.java:107) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.2-822dad7]
	... 15 more
```

**Comment by azbh111** [comment]
@Zilacon  Build #366 fix hd
